app:
    resource: '@AppBundle/Controller/'
    type: annotation

user_rest:
    type: rest
    resource: "@AppBundle/Controller/UserApiController.php"
    prefix: "/api"

entry_rest:
    type: rest
    resource: "@AppBundle/Controller/EntryApiController.php"
    prefix: "/api"


activity_rest:
    type: rest
    resource: "@AppBundle/Controller/ActivityApiController.php"
    prefix: "/api"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app.swagger_ui:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /documentation
