security:
    encoders:
        FOS\UserBundle\Model\UserInterface:
            algorithm: bcrypt
            cost: 10

    role_hierarchy:
        # ROLE_USER
        # ROLE_API
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        api_provider:
            id: app.security.user_provider

    firewalls:
        api:
            pattern: ^/api
            stateless: true
            provider: api_provider
            guard:
              authenticator: AppBundle\Security\TokenAuthenticator

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/documentation, role: ROLE_USER }
        - { path: ^/api, role: ROLE_API }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/register/confirmed, role: ROLE_USER }
        - { path: ^/register, role: ROLE_ADMIN }
        - { path: ^/resetting, role: ROLE_ADMIN }
        - { path: ^/profile, role: ROLE_ADMIN }